include:
  - path: ../vm-networks/compose.yml

services:
  clickup-tg:
    container_name: clickup-tg
    image: alpine
    command: sh -c 'while [ ! -f /tmp/sops/temp/file ]; do sleep 1; done; cat $(cat /tmp/sops/temp/file); rm /tmp/sops/temp/file'
    # entrypoint: sleep infinity
    depends_on:
      - sops
    networks:
      edge: {}
      dmz: {}
    volumes:
      - /tmp/sops/temp:/tmp/sops/temp
      - /tmp/sops:/tmp:ro

  sops:
    container_name: sops
    image: ghcr.io/getsops/sops:v3.8.1-alpine
    command: exec-file /secrets/secrets.json 'echo {} > /tmp/sops/temp/file; while [ -f /tmp/sops/temp/file ]; do sleep 1; done'
    volumes:
      - ../vm-clickup-tg:/secrets:ro
      - /root/.config/sops/age/keys.txt:/root/.config/sops/age/keys.txt:ro
      - /tmp/sops/temp:/tmp/sops/temp
      - /tmp/sops:/tmp
    network_mode: none
