export {mocks, updates, values};

const chatId = '123456789';
const fileContent = 'some jpg data';
const filename1 = 'file_1.jpg';
const filename2 = 'file_2.jpg';
const message = 'hola, mundo';
const prefix = '/tg';
const taskId = '8693b10w6';
const userId = 12345678;
const username = 'jdoe';
const email = `${username}@domain.org`;

const values = {chatId, taskId, username};

const updates = {
  attachment: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920969807432438536',
        'type': 1,
        'date': '2024-03-03T22:15:52.158Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617847',
        'comment': {
          'id': '90120028617847',
          'date': '1709504152158',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${prefix} `,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-10f51383-e737-45c7-afa8-652e2be31285',
              },
            },
            {
              'type': 'attachment',
              'text': filename1,
              'attachment': {
                'id': '14b4dbbe-7a0c-4560-8486-a31b52425bb5.jpg',
                'date': '1707840694395',
                'title': filename1,
                'type': 2,
                'source': 1,
                'version': 0,
                'extension': 'jpg',
                'thumbnail_small': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_small.jpg',
                'thumbnail_medium': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_medium.jpg',
                'thumbnail_large': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'is_folder': null,
                'mimetype': 'image/jpeg',
                'hidden': false,
                'parent_id': '90120028617847',
                'size': 5918,
                'total_comments': 0,
                'resolved_comments': 0,
                'user': {
                  'id': userId,
                  'username': username,
                  'email': email,
                  'initials': 'A',
                  'color': '#595d66',
                  'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
                },
                'deleted': false,
                'orientation': '1',
                'url': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'parent_comment_type': 1,
                'parent_comment_parent': taskId,
                'email_data': null,
                'url_w_query': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}?view=open`,
                'url_w_host': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
              },
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-55f22753-5305-4084-a165-38da80b71a0e',
              },
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-3ea8a3bb-205d-4d03-b0f5-fa6b19eb55ea',
              },
            },
          ],
          'text_content': `${prefix} \n${filename1}\n\n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617847',
            'vector': [
              {
                'master_id': 15,
                'version': 1709504152200000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  attachmentComment: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920969807432438536',
        'type': 1,
        'date': '2024-03-03T22:15:52.158Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617847',
        'comment': {
          'id': '90120028617847',
          'date': '1709504152158',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${prefix} ${message}`,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-750b8f5b-9b55-4751-910d-14cb62c10f73',
              },
            },
            {
              'type': 'attachment',
              'text': filename1,
              'attachment': {
                'id': '14b4dbbe-7a0c-4560-8486-a31b52425bb5.jpg',
                'date': '1707840694395',
                'title': filename1,
                'type': 2,
                'source': 1,
                'version': 0,
                'extension': 'jpg',
                'thumbnail_small': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_small.jpg',
                'thumbnail_medium': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_medium.jpg',
                'thumbnail_large': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'is_folder': null,
                'mimetype': 'image/jpeg',
                'hidden': false,
                'parent_id': '90120028617847',
                'size': 5918,
                'total_comments': 0,
                'resolved_comments': 0,
                'user': {
                  'id': userId,
                  'username': username,
                  'email': email,
                  'initials': 'A',
                  'color': '#595d66',
                  'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
                },
                'deleted': false,
                'orientation': '1',
                'url': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'parent_comment_type': 1,
                'parent_comment_parent': taskId,
                'email_data': null,
                'url_w_query': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}?view=open`,
                'url_w_host': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
              },
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-55f22753-5305-4084-a165-38da80b71a0e',
              },
            },
          ],
          'text_content': `${prefix} ${message}\n${filename1}\n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617847',
            'vector': [
              {
                'master_id': 15,
                'version': 1709504152200000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  attachmentOnly: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920969807432438536',
        'type': 1,
        'date': '2024-03-03T22:15:52.158Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617847',
        'comment': {
          'id': '90120028617847',
          'date': '1709504152158',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${prefix} `,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-750b8f5b-9b55-4751-910d-14cb62c10f73',
              },
            },
            {
              'type': 'attachment',
              'text': filename1,
              'attachment': {
                'id': '14b4dbbe-7a0c-4560-8486-a31b52425bb5.jpg',
                'date': '1707840694395',
                'title': filename1,
                'type': 2,
                'source': 1,
                'version': 0,
                'extension': 'jpg',
                'thumbnail_small': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_small.jpg',
                'thumbnail_medium': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_medium.jpg',
                'thumbnail_large': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'is_folder': null,
                'mimetype': 'image/jpeg',
                'hidden': false,
                'parent_id': '90120028617847',
                'size': 5918,
                'total_comments': 0,
                'resolved_comments': 0,
                'user': {
                  'id': userId,
                  'username': username,
                  'email': email,
                  'initials': 'A',
                  'color': '#595d66',
                  'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
                },
                'deleted': false,
                'orientation': '1',
                'url': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'parent_comment_type': 1,
                'parent_comment_parent': taskId,
                'email_data': null,
                'url_w_query': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}?view=open`,
                'url_w_host': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
              },
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-55f22753-5305-4084-a165-38da80b71a0e',
              },
            },
          ],
          'text_content': `${prefix} \n${filename1}\n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617847',
            'vector': [
              {
                'master_id': 15,
                'version': 1709504152200000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  attachments: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920969807432438536',
        'type': 1,
        'date': '2024-03-03T22:15:52.158Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617847',
        'comment': {
          'id': '90120028617847',
          'date': '1709504152158',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${prefix} `,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-750b8f5b-9b55-4751-910d-14cb62c10f73',
              },
            },
            {
              'type': 'attachment',
              'text': filename1,
              'attachment': {
                'id': '14b4dbbe-7a0c-4560-8486-a31b52425bb5.jpg',
                'date': '1707840694395',
                'title': filename1,
                'type': 2,
                'source': 1,
                'version': 0,
                'extension': 'jpg',
                'thumbnail_small': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_small.jpg',
                'thumbnail_medium': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_medium.jpg',
                'thumbnail_large': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'is_folder': null,
                'mimetype': 'image/jpeg',
                'hidden': false,
                'parent_id': '90120028617847',
                'size': 5918,
                'total_comments': 0,
                'resolved_comments': 0,
                'user': {
                  'id': userId,
                  'username': username,
                  'email': email,
                  'initials': 'A',
                  'color': '#595d66',
                  'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
                },
                'deleted': false,
                'orientation': '1',
                'url': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
                'parent_comment_type': 1,
                'parent_comment_parent': taskId,
                'email_data': null,
                'url_w_query': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}?view=open`,
                'url_w_host': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename1}`,
              },
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-55f22753-5305-4084-a165-38da80b71a0e',
              },
            },
            {
              'type': 'attachment',
              'text': filename2,
              'attachment': {
                'id': '14b4dbbe-7a0c-4560-8486-a31b52425bb5.jpg',
                'date': '1707840694395',
                'title': filename2,
                'type': 2,
                'source': 1,
                'version': 0,
                'extension': 'jpg',
                'thumbnail_small': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_small.jpg',
                'thumbnail_medium': 'https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5_medium.jpg',
                'thumbnail_large': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename2}`,
                'is_folder': null,
                'mimetype': 'image/jpeg',
                'hidden': false,
                'parent_id': '90120028617847',
                'size': 5918,
                'total_comments': 0,
                'resolved_comments': 0,
                'user': {
                  'id': userId,
                  'username': username,
                  'email': email,
                  'initials': 'A',
                  'color': '#595d66',
                  'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
                },
                'deleted': false,
                'orientation': '1',
                'url': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename2}`,
                'parent_comment_type': 1,
                'parent_comment_parent': taskId,
                'email_data': null,
                'url_w_query': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename2}?view=open`,
                'url_w_host': `https://t1234567890.p.clickup-attachments.com/t1234567890/14b4dbbe-7a0c-4560-8486-a31b52425bb5/${filename2}`,
              },
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-3ea8a3bb-205d-4d03-b0f5-fa6b19eb55ea',
              },
            },
          ],
          'text_content': `${prefix} \n${filename1}\n${filename2}\n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617847',
            'vector': [
              {
                'master_id': 15,
                'version': 1709504152200000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  comment: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920969807432438536',
        'type': 1,
        'date': '2024-03-03T22:15:52.158Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617847',
        'comment': {
          'id': '90120028617847',
          'date': '1709504152158',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${prefix} ${message}`,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-750b8f5b-9b55-4751-910d-14cb62c10f73',
              },
            },
          ],
          'text_content': `${prefix} ${message}\n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617847',
            'vector': [
              {
                'master_id': 15,
                'version': 1709504152200000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  commentEmpty: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920969807432438536',
        'type': 1,
        'date': '2024-03-03T22:15:52.158Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617847',
        'comment': {
          'id': '90120028617847',
          'date': '1709504152158',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${prefix} `,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-10f51383-e737-45c7-afa8-652e2be31285',
              },
            },
          ],
          'text_content': `${prefix} \n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617847',
            'vector': [
              {
                'master_id': 15,
                'version': 1709504152200000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  notTg: {
    'event': 'taskCommentPosted',
    'history_items': [
      {
        'id': '3920954036497083724',
        'type': 1,
        'date': '2024-03-03T22:00:12.138Z',
        'field': 'comment',
        'parent_id': '901200528379',
        'data': {},
        'source': null,
        'user': {
          'id': userId,
          'username': username,
          'email': email,
          'color': '#595d66',
          'initials': 'A',
          'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
        },
        'before': null,
        'after': '90120028617410',
        'comment': {
          'id': '90120028617410',
          'date': '1709503212138',
          'parent': taskId,
          'type': 1,
          'comment': [
            {
              'text': `${message}`,
              'attributes': {},
            },
            {
              'text': '\n',
              'attributes': {
                'block-id': 'block-750b8f5b-9b55-4751-910d-14cb62c10f73',
              },
            },
          ],
          'text_content': `${message}\n`,
          'x': null,
          'y': null,
          'image_y': null,
          'image_x': null,
          'page': null,
          'comment_number': null,
          'comment_time': null,
          'referenced_content': '',
          '_version_vector': {
            'workspace_id': 1234567890,
            'object_type': 'comment',
            'object_id': '90120028617410',
            'vector': [
              {
                'master_id': 15,
                'version': 1709503212168000,
                'deleted': false,
              },
            ],
          },
          'comment_type': null,
          'page_id': null,
          'page_name': null,
          'view_id': null,
          'view_name': null,
          'team': null,
          'view_parent_id': null,
          'user': {
            'id': userId,
            'username': username,
            'email': email,
            'color': '#595d66',
            'initials': 'A',
            'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
          },
          'new_thread_count': 0,
          'new_mentioned_thread_count': 0,
          'email_attachments': [],
          'threaded_users': [],
          'threaded_replies': 0,
          'threaded_assignees': 0,
          'threaded_assignees_members': [],
          'threaded_unresolved_count': 0,
          'thread_followers': [
            {
              'id': userId,
              'username': username,
              'email': email,
              'color': '#595d66',
              'initials': 'A',
              'profilePicture': `https://attachments.clickup.com/profilePictures/${userId}_nle.jpg`,
            },
          ],
          'group_thread_followers': [],
          'reactions': [],
          'emails': [],
        },
      },
    ],
    'task_id': taskId,
    'webhook_id': 'df1bddc9-dac9-40e7-a5c5-3b468d240022',
  },
  taskDeleted: {
    'event': 'taskDeleted',
    'task_id': taskId,
    'webhook_id': '7fa3ec74-69a8-4530-a251-8a13730bd204',
  },
};

const mocks = {
  [filename1]: {
    undefined: fileContent,
  },
  [filename2]: {
    undefined: fileContent,
  },
  sendDocument: {
    [JSON.stringify(updates.attachmentComment)]: (() => {
      const form = new FormData();
      form.append('chat_id', chatId);
      form.append('document', new Blob([fileContent]), filename1);
      return form;
    })(),
    [JSON.stringify(updates.attachmentOnly)]: (() => {
      const form = new FormData();
      form.append('chat_id', chatId);
      form.append('document', new Blob([fileContent]), filename1);
      return form;
    })(),
    [filename1]: (() => {
      const form = new FormData();
      form.append('chat_id', chatId);
      form.append('document', new Blob([fileContent]), filename1);
      return form;
    })(),
    [filename2]: (() => {
      const form = new FormData();
      form.append('chat_id', chatId);
      form.append('document', new Blob([fileContent]), filename2);
      return form;
    })(),
  },
  sendMessage: {
    [JSON.stringify(updates.attachmentComment)]: {
      chat_id: chatId,
      text: message,
      parse_mode: 'MarkdownV2',
      disable_notification: false,
    },
    [JSON.stringify(updates.comment)]: {
      chat_id: chatId,
      text: message,
      parse_mode: 'MarkdownV2',
      disable_notification: false,
    },
  },
};
